database:
  name: leave-db
  plan: free

services:
  - type: web
    name: leaveportal
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: leave-db
          property: connectionString
